### Pytorch is a lightweight deep learning framework which is aimed to quickly turn research into prototypes to production deployment. It is open source library developed at Facebook. 

### These tensor operations are the most basics ones which are frequently
- torch.randn
- torch.matmul
- torch.dot
- torch.from_numpy
- torch.to_numpy

In [3]:
# Import required libraries
import numpy as np
import torch

## Function 1 - torch.randn

The `rand` function generates a tensor filled with date generated from a normal distribution. This distribution has mean  zero and standard deviation 1.

In [4]:
# Example 1 - working
x= torch.randn((4), dtype= torch.float)
x

tensor([-0.0961, -0.7678,  0.7998, -1.2546])

The above example generates a tensor of 4 values of type `float`from a random normal distribution.

In [5]:
# Example 2 - working
x= torch.randn((3,2), dtype= torch.float64)
x

tensor([[-2.1890, -0.4997],
        [ 0.3918,  2.0366],
        [ 0.1585,  0.4631]], dtype=torch.float64)

Here, we gave a shape of 3 rows and 2 columns and it generated a random normal distribution tensor of type `float64`.

In [6]:
# Example 3 - breaking 
x= torch.rand((4), dtype=torch.int) 
x

RuntimeError: _th_uniform_ not supported on CPUType for Int

The datatype `int` is not supported by randn.

**Conclusion**
The `randn` function can be of great help to initialize a tensor of a random normal distribution.

## Function 2 - torch.matmul

The `matmul` function returns the dot product of tensors. 

In [7]:
# Example 1 - working
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
c = a.matmul(b)
c

tensor(32)

If both the tensors are 1 dimensional, the result is a scalar.

In [8]:
# Example 2 - working
a = torch.tensor([[1,2],
                  [4,5]])
b = torch.tensor([[4,5],
                  [7,8]])
c = torch.matmul(a,b)
c                

tensor([[18, 21],
        [51, 60]])

The above matmul operation returns a simple matrix multiplication of 2 matrices.

In [9]:
# Example 3 - breaking 
a = torch.tensor([[1,2, 3],
                  [4,5, 6]])
b = torch.tensor([[4,5,6],
                  [7,8, 9]])
torch.matmul(a,b)

RuntimeError: size mismatch, m1: [2 x 3], m2: [2 x 3] at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorMath.cpp:41

The above example failed because of the size mismatch.    
**Golden rule for matrix multiplication**: The number of columns of the left tensor should be equal to the number of rows of the right tensor.

**Conclusion** The `matmul` function is extremely useful for multiplication of matrices. For example, input and weight matrices.

## Function 3 - torch.dot

The `dot` function performs dot product of 1D tensors. <font color = 'red' >torch.dot() behaves differently to np.dot()</font>

In [10]:
# Example 1 - working
a = torch.tensor([1,2,3])
b = torch.tensor([5,6,7])
a.dot(b)

tensor(38)

The dot product of 1D tensors is a scalar.

In [11]:
# Example 2 - working
a = torch.tensor([1,2,3])
b = torch.tensor([5,6,7]).T
a.dot(b)

tensor(38)

We multiply 2 1d tensors.

In [12]:
# Example 3 - breaking 
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([[5,6,7],
                  [8,9,10]])
a.dot(b)

RuntimeError: 1D tensors expected, got 2D, 2D tensors at C:\cb\pytorch_1000000000000\work\aten\src\TH/generic/THTensorEvenMoreMath.cpp:431

torch.dot() means inner product, it needs two tensor 1 D. If you want to do matrix product, you can use torch.mm 

**Conclusion:** The `torch.dot()` should only be used for 1d tensor multiplication.

## Function 4 - torch.from_numpy

The `from_numpy` converts a numpy ndarray to a tensor.

In [13]:
# Example 1 - working
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [14]:
del b

In [15]:
b = torch.from_numpy(a)
print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([1, 2, 3], dtype=torch.int32)


In the above example, we converted a numpy array to a 1d tensor.

In [16]:
# Example 2 - working
a = np.array([[[1,2,3],
              [4,5,6]],
                 [[1,2,3],
                  [4,5,6]]])
print(type(a))
print(a)
b = torch.from_numpy(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'torch.Tensor'>
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]], dtype=torch.int32)


We converted a numpy 3d array to a 3d tensor.

In [17]:
# Example 3 - breaking 
a = np.array(["one","two","three"])
print(type(a))
print(a)
b = torch.from_numpy(a)
print(type(b))
print(b)

<class 'numpy.ndarray'>
['one' 'two' 'three']


TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

We cannot convert a string tensor to a float/ int array.

**Conclusion** The `from_numpy` function can be used if we need to convert numpy ndarray to a tensor if they are required to be executed on GPU.

## Function 5 - torch.numpy

The `numpy` converts a tensor to a numpy ndarray

In [18]:
# Example 1 - working
a = torch.tensor([[1,2,3],
                  [4,5,6]])
print(type(a))
print(a)
b = a.numpy()
print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


Here, we converted a 2d tensor object to a numpy 2*3 ndarray

In [19]:
# Example 2 - working
a = torch.tensor([1,2,3])
print(type(a))
print(a)
b = a.numpy()
print(type(b))
print(b)

<class 'torch.Tensor'>
tensor([1, 2, 3])
<class 'numpy.ndarray'>
[1 2 3]


Here, we converted 1d tensor to a 1d numpy array

In [20]:
# Example 3 - breaking 
a = torch.tensor(["one","two","three"])
print(type(a))
print(a)
b = a.numpy()
print(type(b))
print(b)

ValueError: too many dimensions 'str'

There is no string tensor so you cannot directly convert to pytorch tensor of strings. Alternative, you can convert the string to ASCII char values and save that as a Tensor. [Source](https://stackoverflow.com/a/59344339/3187537)

**Conclusion** The `numpy` function can be used if we need to convert our tensors to numpy ndarray if they are required to be executed on CPU.

## Conclusion

The functions discussed above are extremly useful in implementing neural networks. Understanding basic functionality and their shortcomings can be beneficial to correctly use the functions in the right context.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://stackoverflow.com/questions/44524901/how-to-do-product-of-matrices-in-pytorch

In [21]:
!pip install jovian --upgrade --quiet

In [22]:
import jovian

<IPython.core.display.Javascript object>

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


[jovian] Error: Failed to detect notebook filename. Please provide the correct notebook filename as the "filename" argument to "jovian.commit".
